### ISSUE TITLE
Erro Monitoramento

### ISSUE THREAD

**Issue by samuelfac** [DarkSupremo/LegendasTvDownloader#1]
Ao abrir Menu>Monitoramento
ocorre o seguinte erro:

Consulte o final desta mensagem para obter detalhes sobre como chamar a 
depuração just-in-time (JIT) em vez desta caixa de diálogo.

*************\* Texto de Exceção **************
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: n. Path '', line 0, position 0.
   em Newtonsoft.Json.JsonTextReader.ParseValue()
   em Newtonsoft.Json.JsonTextReader.ReadInternal()
   em Newtonsoft.Json.JsonTextReader.Read()
   em Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   em Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   em Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   em Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   em Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   em Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   em LegendasTvDownloader.Monitoramento.updateList()
   em LegendasTvDownloader.Monitoramento.Monitoramento_Shown(Object sender, EventArgs e)
   em System.Windows.Forms.Form.OnShown(EventArgs e)
   em System.Windows.Forms.Form.CallShownEvent()
   em System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   em System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   em System.Threading.ExecutionContext.runTryCode(Object userData)
   em System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   em System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   em System.Windows.Forms.Control.InvokeMarshaledCallbacks()

*************\* Conjuntos de Módulos (Assemblies) Carregados **************
mscorlib
    Versão do Conjunto de Módulos (Assembly): 2.0.0.0
    Versão do Win32: 2.0.50727.5477 (Win7SP1GDR.050727-5400)
##     Base de Código: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll

LegendasTv
    Versão do Conjunto de Módulos (Assembly): 1.6.0.0
    Versão do Win32: 1.6.0.0
##     Base de Código: file:///D:/Arquivos/Downloads/LegendasTV.2.4/LegendasTv.exe

System.Windows.Forms
    Versão do Conjunto de Módulos (Assembly): 2.0.0.0
    Versão do Win32: 2.0.50727.5468 (Win7SP1GDR.050727-5400)
##     Base de Código: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Versão do Conjunto de Módulos (Assembly): 2.0.0.0
    Versão do Win32: 2.0.50727.5467 (Win7SP1GDR.050727-5400)
##     Base de Código: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Versão do Conjunto de Módulos (Assembly): 2.0.0.0
    Versão do Win32: 2.0.50727.5467 (Win7SP1GDR.050727-5400)
##     Base de Código: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

Microsoft.VisualBasic
    Versão do Conjunto de Módulos (Assembly): 8.0.0.0
    Versão do Win32: 8.0.50727.5420 (Win7SP1.050727-5400)
##     Base de Código: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualBasic/8.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll

System.Configuration
    Versão do Conjunto de Módulos (Assembly): 2.0.0.0
    Versão do Win32: 2.0.50727.5476 (Win7SP1GDR.050727-5400)
##     Base de Código: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Core
    Versão do Conjunto de Módulos (Assembly): 3.5.0.0
    Versão do Win32: 3.5.30729.5420 built by: Win7SP1
##     Base de Código: file:///C:/Windows/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll

System.Xml
    Versão do Conjunto de Módulos (Assembly): 2.0.0.0
    Versão do Win32: 2.0.50727.5476 (Win7SP1GDR.050727-5400)
##     Base de Código: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll

System.Runtime.Remoting
    Versão do Conjunto de Módulos (Assembly): 2.0.0.0
    Versão do Win32: 2.0.50727.5420 (Win7SP1.050727-5400)
##     Base de Código: file:///C:/Windows/assembly/GAC_MSIL/System.Runtime.Remoting/2.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll

mscorlib.resources
    Versão do Conjunto de Módulos (Assembly): 2.0.0.0
    Versão do Win32: 2.0.50727.5477 (Win7SP1GDR.050727-5400)
##     Base de Código: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll

Newtonsoft.Json
    Versão do Conjunto de Módulos (Assembly): 6.0.0.0
    Versão do Win32: 6.0.3.17227
##     Base de Código: file:///D:/Arquivos/Downloads/LegendasTV.2.4/Newtonsoft.Json.DLL

System.ComponentModel.DataAnnotations
    Versão do Conjunto de Módulos (Assembly): 3.5.0.0
    Versão do Win32: 3.5.30729.5420
##     Base de Código: file:///C:/Windows/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/3.5.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll

System.Runtime.Serialization
    Versão do Conjunto de Módulos (Assembly): 3.0.0.0
    Versão do Win32: 3.0.4506.5452 (Win7SP1GDR.030729-5400)
##     Base de Código: file:///C:/Windows/assembly/GAC_MSIL/System.Runtime.Serialization/3.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

System.Xml.Linq
    Versão do Conjunto de Módulos (Assembly): 3.5.0.0
    Versão do Win32: 3.5.30729.5420 built by: Win7SP1
##     Base de Código: file:///C:/Windows/assembly/GAC_MSIL/System.Xml.Linq/3.5.0.0__b77a5c561934e089/System.Xml.Linq.dll

System.Data
    Versão do Conjunto de Módulos (Assembly): 2.0.0.0
    Versão do Win32: 2.0.50727.5420 (Win7SP1.050727-5400)
##     Base de Código: file:///C:/Windows/assembly/GAC_32/System.Data/2.0.0.0__b77a5c561934e089/System.Data.dll

System.Windows.Forms.resources
    Versão do Conjunto de Módulos (Assembly): 2.0.0.0
    Versão do Win32: 2.0.50727.5420 (Win7SP1.050727-5400)
##     Base de Código: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms.resources/2.0.0.0_pt-BR_b77a5c561934e089/System.Windows.Forms.resources.dll

*************\* Depuração JIT **************
Para habilitar a depuração just-in-time (JIT), o arquivo .config deste
aplicativo ou computador (machine.config) deve ter o valor
jitDebugging definido na seção system.windows.forms.
O aplicativo também deve ser compilado com a depuração
habilitada.

Por exemplo:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Quando a depuração JIT está habilitada, qualquer exceção não tratada
será enviada ao depurador JIT registrado no computador,
em vez de ser tratada nesta caixa de diálogo.

**Comment by henriquelbsouza** [comment]
@DarkSupremo 
Cara, aproveitando a issue desta tela, ao tentar excluir mais de um monitoramento (esteja ele finalizado ou não), excluí apenas o primeiro corretamente, o restante se perde, provavelmente por utilizar a posição do array.

Ex: quero excluir os monitoramentos 5 6 e 7 (sendo que 7 é o ultimo)
Ele excluí a 5, a 7 e da erro 
no caso pulou a 6 por agora ser 5, excluiu a 7 por ser a 'nova' 6 e deu erro ao tentar excluir o numero 7 por não existir mais.


Att.
