### ISSUE TITLE
Arquivos zip com pastas

### ISSUE THREAD

**Issue by henriquelbsouza** [DarkSupremo/LegendasTvDownloader#2]
Fiz o download de algumas legendas (modern family ultima temporada) e dentro dos arquivos zip tinham pastas, com isso não descompactou sozinho, baixou apenas o arquivo compactado na pasta.

Seria possível fazer uma verificação de arquivos, se for diretório entrar nele e buscar a legenda ideal, como já funciona hoje.

Nunca trabalhei com C#, mas posso parear se alguém estiver afim de resolver isso...

Deve ser rápido =)

**Comment by DarkSupremo** [comment]
Issue corrigida: https://github.com/DarkSupremo/LegendasTvDownloader/releases/tag/3.2.3

**Comment by henriquelbsouza** [comment]
Awesome, thanks :)

**Comment by samuelfac** [comment]
acabei de baixar a ultima versão (https://github.com/uilton-oliveira/LegendasTvDownloader/releases/download/v2021-08-12-897895ae/win_x64.zip) coloquei para baixar a legenda de "The.Good.Doctor.S05E12" e somente descompactou a pasta de dentro do arquivo zip. 

teria como extrair as legendas na mesma pasta do video?
