### ISSUE TITLE
Alguma previsão, ou intenção para linux?

### ISSUE THREAD

**Issue by RyuunosukeDS3** [darksupremo/LegendasTvDownloader#7]
Tenho um raspberrypi rodando plex em docker. Gostaria de baixar as legendas diretamente do raspberry. Seria factivel?

**Comment by darksupremo** [comment]
@RyuunosukeDS3 Você pretende fazer de alguma forma automatizada? se sim, acho que esse projeto não seria muito apropriado pra isso, acho que com o https://github.com/darksupremo/legendas.tv-api seria mais fácil, mas teria que criar algum script pra integrar com a api...

Já existe um projeto que talvez lhe atenda, da uma olhada: https://www.bazarr.media/

**Comment by RyuunosukeDS3** [comment]
Opa! Chegando em casa vou dar uma testada. Valeu!

**Comment by RyuunosukeDS3** [comment]
Opa! Chegando em casa vou dar uma testada. Valeu!
